### ISSUE TITLE
Include CA bundle with wildcard cert in key vault

### ISSUE THREAD

**Issue by AAkindele** [retaildevcrews/aks-secure-baseline-hack-template#127]
When using the current wildcard cert from key vault with Traefik, only the primary cert is pulled from key vault and saved to tls.crt in the pods. This causes App Gatgeway to return an error saying the certificate presented by the backend server does not match the certificate on the gateway.
This was manually resolved by creating a new secret that combined the ca bundle and the cert in a new key that Traefik can use for tls.crt.

Error message from the gateway when Traefik is using the tls.crt without the CA bundle
```txt
The root certificate of the server certificate used by the backend does not match the trusted root certificate added to the application gateway. Ensure that you add the correct root certificate to whitelist the backend
```

The original configuration for the secretproviderclass can be found here for pulling the tls.crt directly from the certificate resource in key vault. https://github.com/mspnp/aks-secure-baseline/blob/main/08-secret-managment-and-ingress-controller.md

```yaml
      array:
        - |
          objectName: traefik-ingress-internal-aks-ingress-contoso-com-tls
          objectAlias: tls.crt
          objectType: cert
```

How can the certificate be imported to key vault, so that pulling the cert into tls.crt includes the bundle that is expected by App Gateway?
